/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, FormDataInput } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IUpload } from "../structures/IUpload";

/**
 * @controller AppController.upload
 * @path POST /upload
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function upload(
  connection: IConnection,
  body: upload.Input,
): Promise<void> {
  return PlainFetcher.fetch(
    connection,
    {
      ...upload.METADATA,
      template: upload.METADATA.path,
      path: upload.path(),
    },
    body,
  );
}
export namespace upload {
  export type Input = FormDataInput<IUpload>;

  export const METADATA = {
    method: "POST",
    path: "/upload",
    request: {
      type: "multipart/form-data",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/upload";
}
